<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container7sLj4Oo\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container7sLj4Oo/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container7sLj4Oo.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container7sLj4Oo\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container7sLj4Oo\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '7sLj4Oo',
    'container.build_id' => '5e189154',
    'container.build_time' => 1645717180,
], __DIR__.\DIRECTORY_SEPARATOR.'Container7sLj4Oo');
